import argparse

parser = argparse.ArgumentParser(description='COME')
parser.add_argument('--feat-extractor', default='i3d', choices=['i3d', 'c3d'])
parser.add_argument('--modality', default='RGB', help='the type of the input, RGB,AUDIO, or MIX')
parser.add_argument('--gpus', default=1, type=int, choices=[0], help='gpus')
parser.add_argument('--lr', type=str, default='[0.0001]*60000', help='learning rates for steps(list form)')
parser.add_argument('--BS', type=int, default=64, help='number of instances in a batch of data (default: 16)')
parser.add_argument('--FEATS_DIM', type=int, default=1024, help='size of feature (default: 2048)')
parser.add_argument('--EMBED_FEATS_DIM', type=int, default=512, help='size of feature (default: 2048)')
parser.add_argument('--workers', default=4, help='number of workers in dataloader')
parser.add_argument('--model-name', default='come', help='name to save model')
parser.add_argument('--pretrained-ckpt', default=None, help='ckpt for pretrained model')
parser.add_argument('--num-classes', type=int, default=1, help='number of class')
parser.add_argument('--dataset', default='ucf', help='dataset to train on (default: )')
parser.add_argument('--plot-freq', type=int, default=10, help='frequency of plotting (default: 10)')
parser.add_argument('--max-epoch', type=int, default=60000, help='maximum iteration to train (default: 100)')
parser.add_argument('--num_segments', type=int, default=320, help='number of segments per video')
parser.add_argument('--crops', type=int, default=1, help='')
parser.add_argument('--seed', type=int, default=1234, help='')
parser.add_argument('--debug', action='store_true')
